stickers = [
    'CAACAgIAAxkBAAIPUWJPAnqbIzXfc6j29UYHbEalfkzUAAJYGAACo-_xSQfWaCf9QzsBIwQ',
    'CAACAgIAAxkBAAIPVGJPA12b9o55mwbrMzoB2ny2mawnAALdFgAChMvxSW7PJ8RlPUdLIwQ',
    'CAACAgIAAxkBAAIPWGJPA8o8k8QKlkRj_eu2CA3x51LpAAKgGAAC1I_wSQ5xG33_z33cIwQ',
    'CAACAgIAAxkBAAIPWmJPA-gynrSrFQa0nFea2NIfChGrAAITGgAC4LfwSRdCTu0_QG3LIwQ',
    'CAACAgIAAxkBAAIPvGJPBzQ6QQIyfMNSnV-GslEUjmwyAAKiGAACKBjwSerdE3KxhW6IIwQ',
]
